 thumbnails:
  - width: 80
    prefix: icon_
    include:
    - '*.png'
    - '*.jpg'
  - width: 200
    prefix: page_
    include:
    - '*.png'
    - '*.jpg'
  - height: 500
    prefix: box_
    include:
    - '*.png'
    - '*.jpg'
